### ISSUE TITLE
How to enable logger in production?

### ISSUE THREAD

**Issue by ofertacom** [dart-lang/logging#114]
Hi there! 
Is there a way to enable logger in the production environment?

**Comment by johntimothybailey** [comment]
@ofertacom What am I missing? It doesn't seem to have any specific code for App flavors. What do you mean by production "environment" beyond the flavors?

**Comment by devoncarew** [comment]
@ofertacom - this package is essentially orthogonal to how to enable in various environments. You'd want your app to listen to the root logger, and have a way to record / display log messages that is sees.
