### ISSUE TITLE
LogRecord should be using Clock so that way the log time can be tested

### ISSUE THREAD

**Issue by robert-j-webb** [dart-lang/logging#116]
Currently LogRecord uses `DateTime.now()` to get the current time. This makes logging untestable because we can't overwrite DateTime.now()

Instead it should be using `clock.now()` which can be overwritten with `withClock`. [Clock dart package](https://pub.dev/documentation/clock/latest/)

I can write a PR for this, it's a pretty simple change.

**Comment by devoncarew** [comment]
This is a pretty low-level package, so we have to be very careful of the dependencies we take (currently, `logging` doesn't have any regular dependencies).

An alternative would be to have a way to inject the time service that logging should use?

cc'ing @natebosch for thoughts on taking a dep on package:clock vs something like providing an optional `getTime` callback in Logger's constructor.

**Comment by natebosch** [comment]
> in Logger's constructor.

I don't know if that will give a very ergonomic experience, it would require rewriting potentially many `Logger` constructor calls, and dealing with passing the `Clock` in many places in your code. It's quite common for `Logger` instances to be static.

The `withClock` utility uses a zone variable IIRC, which wouldn't be as invasive in the production code.

I'm curious why the `time` on the record objects is an important aspect to test?

**Comment by robert-j-webb** [comment]
Yes, the overhead should be pretty minor but I do understand not having any dependencies being important for a widely used library. 

I wanted to make some test code that would validate that logs were happening, but I achieved that by just checking the text. After doing that, I can’t see the use case for testing the log time in a test.
