### ISSUE TITLE
Add "error" and "info"-method to Logger

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/logging#23]
_From @DartBot on July 16, 2013 13:12_

_This issue was originally filed by off...&#064;mikemitterer.at_

---

**What steps will reproduce the problem?**
final Logger logger = new Logger(&quot;rest.DefeaultRESTErrorProcessor&quot;);
logger.error(&quot;Does not work&quot;);

**Please provide any additional information below.**
Most Logging-Frameworks use &quot;error&quot; to print out error-messages.
You use &quot;severe&quot;, this is OK but give us &quot;error&quot; to.

The same with &quot;info&quot; - I don't know who is using fine, finer, finest - means nothing.
fine, finer, finest???? - please provide us with &quot;info&quot; in addition to &quot;fine&quot;

_Copied from original issue: dart-lang/sdk#11845_

**Comment by kevmoo** [comment]
_From @iposva-google on July 16, 2013 15:40_

*Added [Area-Pkg](../labels/Area-Pkg), [Triaged](../labels/Triaged) labels.*

**Comment by kevmoo** [comment]
_From @sigmundch on August 15, 2013 0:0_

*Added [Library-Logging](../labels/Library-Logging) label.*

**Comment by kevmoo** [comment]
_From @anders-sandholm on February 6, 2014 15:13_

*Removed [Library-Logging](../labels/Library-Logging) label.*
*Added [Pkg-Logging](../labels/Pkg-Logging) label.*

**Comment by MikeMitterer** [comment]
:disappointed: 2017!

**Comment by kevmoo** [comment]
@MikeMitterer pull requests welcome 😄

**Comment by jakemac53** [comment]
I am going to close this as not planned, given that we did receive a [pull request](https://github.com/dart-lang/logging/pull/54) and rejected it (at least for now) based on logistical reasons due to the breaking nature of the change.
