### ISSUE TITLE
logging.dart, "autogenerated stack trace for $logLevel $message" is unused.

### ISSUE THREAD

**Issue by haejeong87** [dart-lang/logging#25]
The thrown exception is immediately caught to save the stack trace, but the error message, "autogenerated stack trace for $logLevel $message" is not saved and is never used.
https://github.com/dart-lang/logging/blob/master/lib/logging.dart#L160
This looks like an unintended behavior.

When the argument for "error" parameter is null, please pass the caught error to the instantiated LogRecord at
https://github.com/dart-lang/logging/blob/master/lib/logging.dart#L168

**Comment by sigmundch** [comment]
Hey @haejeong87, thanks for opening this issue. 

This was initially on purpose, but I'd be happy to add it if there is need for it.

The main reason I omitted it is that the information in that string is already available in the log record. We made the string contain a message (and not just an arbitrary exception) to make it easier to recognize this if you are debugging and breaking on every caught exception, but we could have also done `throw ''`.

Could you tell me more about how the current behavior is problematic?

Thanks!

**Comment by haejeong87** [comment]
Thank you for the response.
I see, I think I was just misguided. You're right that all the necessary information is available in the log record. I'll just use that instead.
Closing the issue.

**Comment by haejeong87** [comment]
Hmm... however, it still feels weird to have stacktrace but no error. When the argument for error parameter is null, it is possible to have stacktrace without error. Since error and stacktrace are usually closely related to each other, users would mostly likely to expect an error object when stacktrace is available.
It would be nice to pass the thrown error object to the LogRecord.

**Comment by haejeong87** [comment]
Ping,
Any chance of that you agree with my comment?

Currently, since error can be null even when stacktrace is available, I must write:

    if (logRecord.stacktrace != null) {
      String error = (logRecord.error != null) logRecord.error : logRecord.message;
      reportToServer(error, logRecord.stacktrace);
    }

If error is populated, I could just do

    if (logRecord.error != null) reportToServer(logRecord.error, logRecord.stacktrace);

Firstly, null-checking for error is more logical than null-checking for stacktrace.
Secondly, the additional logic to determine the original message is less beautiful.

**Comment by sigmundch** [comment]
sorry for the delay. You make a good point. let's change it.

**Comment by sigmundch** [comment]
Here is a CL with the change: https://codereview.chromium.org/1284983004/

**Comment by haejeong87** [comment]
It LGTM :)

**Comment by sigmundch** [comment]
All set :) - I published it too, it's now available in pub.dartlang.org
