### ISSUE TITLE
Document that logging methods accept functions

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/logging#31]
When logging messages, you frequently don't want to compute the strings to log unless the log level is set high enough.  I propose the log methods accept functions that produce Strings as well as raw Strings, so the caller can say either of these:

```
logger.fine('simple message');
logger.fine(() => 'complex message: ${large.computation()}');
```

**Comment by tvolkert** [comment]
Ah - I see that this actually already works :-)

Updating the bug description to be about documentation, since the Dartdocs don't mention this feature at all.

**Comment by jamesderlin** [comment]
This is mentioned in the `README.md`:

> When logging more complex messages, you can pass a closure instead that will be
evaluated only if the message is actually logged:

but it's not mentioned for `Logger.fine`, `Logger.info`, `Logger.warning`, etc.  IMO all of those should refer to more general and more thorough documentation.
