### ISSUE TITLE
Adding caller code's location automatically

### ISSUE THREAD

**Issue by yyoon** [dart-lang/logging#32]
In our logging package wrapper, we have some logic to automatically add the file name and the line number of the log method caller, using the `stack_trace` package. It would be nice if the filename and the line number were provided by the logging package itself, as part of the `LogRecord` class.

Roughly our code looks like the following:

```dart
logger.onRecord.listen((LogRecord rec) {
  // ...

  bool inDebugMode = false;
  assert(() {
    inDebugMode = true;
    return true;
  });

  String codeLocation;
  bool showCodeLocation = (forceShowCodeLocation ?? false) || inDebugMode;
  if (showCodeLocation) {
    Trace trace = new Trace.current();
    Frame callerFrame = _findCallerFrame(trace);
    if (callerFrame != null) {
      if (callerFrame.uri.pathSegments.isNotEmpty) {
        String filename = callerFrame.uri.pathSegments.last;
        String line = callerFrame.line != null ? '(${callerFrame.line})' : '';
        codeLocation = '$filename$line';
      }
    }
  }

  // Use the code location below...
});

/// From the given [Trace], find the first [Frame] after the `logging` package
/// and return that frame. If no such [Frame] is found, return [null].
Frame _findCallerFrame(Trace trace) {
  bool foundLogging = false;

  for (int i = 0; i < trace.frames.length; ++i) {
    Frame frame = trace.frames[i];

    bool loggingPackage = frame.package == 'logging';
    if (foundLogging && !loggingPackage) {
      return frame;
    }

    foundLogging = loggingPackage;
  }

  return null;
}
```

Assuming that this is an expensive thing to do, we're only doing it in checked mode for now. Similarly, the logging package could have some configuration (similar to `recordStackTraceAtLevel`).

**Comment by matanlurey** [comment]
This would be somewhat expensive to do, and even in checked mode means it would _potentially_ be run for all developers, always. Maybe instead it makes sense to only attach stack traces to somewhat severe logs?

**Comment by yyoon** [comment]
I was suggesting that this should be an opt-in thing like the `recordStackTraceAtLevel`. Maybe I'm not quite understanding how expensive it is. Would it be okay if we're not spamming logs with this?

Otherwise, whenever we add logging statements, we have to always manually add the filename at least in each log because it's difficult to tell where the log came from.

Also, just using the already existing `LogRecord.stackTrace` variable is not enough, because we can't know for sure whether if the `stackTrace` was generated by the logging package by the `recordStackTraceAtLevel` option, or if it is provided by the caller explicitly.

**Comment by matanlurey** [comment]
Let's chat offline - maybe I can see what we can do for your team. Ping me internally.

**Comment by natebosch** [comment]
`recordStackTraceAtLevel` should be sufficient here. If you set that the stack trace will be included on the `LogRecord` the log listener can handle this for the output. I don't think it's strictly necessary that the `Logger` is the one to do the translation.
