### ISSUE TITLE
Logger.detached does not fire onRecord messages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/logging#34]
It would be nice to document how to catch messages :-/

**Comment by java-james** [comment]
+1 

A detached logger doesn't work as exected if hierarchicalLoggingEnabled is true

For example this logger cannot log:

`
final logger = Logger.detached('DetachedLogger')
..level = Level.ALL
..onRecord.listen((rec) {
print('${rec.level.name}: ${rec.time}: ${rec.message}');
});
  logger.info('test');
`

Error comes from logger.dart line 183 trying to use the root logger which has a null controller if hierarchicalLoggingEnabled is false

**Comment by java-james** [comment]
This is related to hierarchicalLoggingEnabled. If the detached logger isn't a child of the root logger nd hierarchicalLoggingEnabled = false then it will never reach the detached logger. Which can be a little confusing.

For example this logger cannot log:
final logger = Logger.detached('DetachedLogger') ..level = Level.ALL ..onRecord.listen((rec) { print('${rec.level.name}: ${rec.time}: ${rec.message}'); }); logger.info('test');

Error comes from logger.dart line 183 trying to use the root logger (which has a null controller) if hierarchicalLoggingEnabled is false

**Comment by jamesderlin** [comment]
Why is this closed?

1. I don't see any documentation for `Logger.detached` that explains this.  `Logger.detached` purports to be "not a part of the global hierarchical loggers structure", so it doesn't make sense to me that it should be affected by `hierarchicalLoggingEnabled`.
2. I'm confused what purpose `Logger.detached` has if it requires `hierarchicalLoggingEnabled = true`.  That defeats the point of why I want to use `Logger.detached`.

**Comment by jamesderlin** [comment]
Maybe @astashov can comment on the intent of how `Logger.detached` is supposed to be used.

Anyway, if we can agree that this should be fixed, I could take it on.  I think the `level` getter and setter also should be adjusted.
