### ISSUE TITLE
building with dart2js is causing an issue 

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/logging#36]
I am having a strange error with this package after building with dart2js. I believe the error most likley belongs to dart2js so I filed the detailed bug report over at: https://github.com/dart-lang/sdk/issues/31362

Is this something you've seen before? If not, and it's a dart2js issue then just close this.

Thanks

**Comment by pq** [comment]
Closing w/ https://github.com/dart-lang/sdk/issues/31362.

Please re-open if you still have issues!
