### ISSUE TITLE
support groups?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/logging#4]
moved from https://github.com/dart-lang/sdk/issues/13476

> window.console has this feature, and it's really useful.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/console#Using_groups_in_the_console
> 
> ... Polymer uses this for some of its logging. I'm not sure whether to try and match Polymer and use console logging, or try and use Dart's Logger API. One benefit to Logger is I don't need to expose any public APIs related to logging.

**Comment by natebosch** [comment]
Adding this interface to `Logger` would necessarily force additional complexity on log listeners, and we don't plan on trying to ship a set of log listeners that would handle this sanely in different environments. We could imagine providing one that works well on the web, but then we'd have to make decisions about how to handle it in other log listeners, like to `stdout` or across places that ship logs around.

If someone wants to argue for this being something that most log listeners would be safe to ignore we can reconsider.
