### ISSUE TITLE
Print long Strings

### ISSUE THREAD

**Issue by Mantas0726** [dart-lang/logging#41]
Long strings are capped at 1000 chars in Android Studio console and there is no option to increase this limit in AS, could long strings be split?

Something like this maybe?
https://stackoverflow.com/questions/7606077/how-to-display-long-messages-in-logcat/37871980

**Comment by jamesderlin** [comment]
Shouldn't this be handled by whatever your `Logger.onRecord` callback is?  For example, if you're logging to a file, you might not want long strings to be split.

**Comment by natebosch** [comment]
+1. We don't want to hardcode knowledge about how you may use log records in this library and forcefully splitting strings here would be breaking for other use cases where they should not be split.
