### ISSUE TITLE
How to set hierarchicalLoggingEnabled = true?

### ISSUE THREAD

**Issue by jagan999** [dart-lang/logging#45]
This does not seem to be a settable property.

**Comment by java-james** [comment]
You can set it. 

For example:
import 'package:logging/logging.dart' as logging;
logging.hierarchicalLoggingEnabled = true;

**Comment by natebosch** [comment]
You should be able to assign to it as @java-james points out.

**Comment by Idodoqdo** [comment]
> 

This does not work

**Comment by Idodoqdo** [comment]
Please someone tell me the way

**Comment by Idodoqdo** [comment]
`import 'package:datasourses/common/config.dart';
import 'appenders.dart';
import 'package:logging/logging.dart' as logging;
logging.logginghierarchicalLoggingEnabled = true; // Functions must have an explicit list of parameters.
Try adding a parameter list.dart(missing_function_parameters)
The name 'logging' is already used as an import prefix and can't be used to name a top-level element.
Try renaming either the top-level element or the prefix.dart[prefix_collides_with_top_level_member](https://dart.dev/diagnostics/prefix_collides_with_top_level_member)
creators.dart(3, 42): The first definition of this name.

Level chooseLevel(String level) { // logging.Level will be here
  switch (level) {
    case "ALL":
      return Level.ALL;
    case "FINEST":
      return Level.FINEST;
    case "FINER":
      return Level.FINER;
    case "FINE":
      return Level.FINE;
    case "CONFIG":
      return Level.CONFIG;
    case "INFO":
      return Level.INFO;
    case "WARNING":
      return Level.WARNING;
    case "SEVERE":
      return Level.SEVERE;
    case "SHOUT":
      return Level.SHOUT;
    default:
      return Level.OFF;
  }
}


class LoggersCreator {
  final List<LoggerConfig> configs;
  final AppendersCreator appendersCreator;

  LoggersCreator(this.configs, this.appendersCreator) {
       Logger.root.level = Level.ALL; 
  }

  Logger createLogger(String loggerName) {
    LoggerConfig loggerConfig = configs.firstWhere(
      (element) => element.name == loggerName, 
      orElse: () => LoggerConfig(name: '', level: '', appenders: [])
    );
    Logger logger;
    if (loggerConfig.name.isNotEmpty) {
      logger = Logger(loggerConfig.name);
      // Unsupported operation: Please set "hierarchicalLoggingEnabled" to true if you want to change the level on a non-root logger.
      logger.level = chooseLevel(loggerConfig.level); // проблема в том, что он не дает помнять lvl
      logger.onRecord.listen((event) {
        writeLog(List<Appender> appender, LogRecord logRecord) => appender.forEach(
          (element) => element.writeLog(logRecord)
        );
        writeLog([for (final val in loggerConfig.appenders) appendersCreator.createAppenders(val)], event);
      });
      return logger;
    }
    logger = Logger("novalid");
    logger.level = Level.OFF;
    return logger;
  }
}

class AppendersCreator {

  final List<AppenderConfig> configs;

  AppendersCreator(this.configs);

  Appender createAppenders(String appenderName) {
    AppenderConfig appenderConfig = configs.firstWhere((element) => element.name == appenderName, 
    orElse: () => AppenderConfig(''));
    if (appenderConfig.name.isNotEmpty) {
      switch (appenderConfig.runtimeType) {
        case AppenderConsoleConfig :
          return AppenderConsole(appenderConfig.name);
        case AppenderFileConfig :
          return AppenderFile(appenderConfig.name, (appenderConfig as AppenderFileConfig).fileName);
      }
    }
    throw Exception("Appender does not exist");
  }
}`

**Comment by Idodoqdo** [comment]
`  LoggersCreator(this.configs, this.appendersCreator) {
    logging.Logger.root.level = logging.Level.ALL;
    logging.hierarchicalLoggingEnabled = true;
  }
`
I fixed it like this and it worked, but why? Excuse me, I'm new to dart

**Comment by natebosch** [comment]
A statement (like an assignment) cannot be at the top level. It must be in some method.

https://dart.dev/language

**Comment by Hari-07** [comment]
@Idodoqdo you can just set it like it's a global variable, I found it confusing too because it's not namespaced. I think if you import the logging package with an alias it'd be more clear otherwise just doing `hierarchicalLoggingEnabled = true` anywhere in your code should just work

**Comment by Idodoqdo** [comment]
@Hari-07 thanks, i made a mistake trying to set not in function body. Everything worked
`  LoggerFactory._internal() {
    logging.Logger.root.level = logging.Level.ALL;
    logging.hierarchicalLoggingEnabled = true;
  }
`
