### ISSUE TITLE
can logging write text into a file?

### ISSUE THREAD

**Issue by 2741248158** [dart-lang/logging#55]
final g_log = Logger('logging:');

Logger.root.level = Level.ALL;
Logger.root.onRecord.listen((record) {
  print('${record.level.name}: ${record.time}: ${record.message}');
});

g_log.warning((){return 'hello logging';});

-------
this can only write log to console?

can logging support write logs into a specified file?
or even specify a file max size, like log4j?

eg:
String file_path = './my.log';
g_log.set_output_file_path(file_path);
g_log.set_max_file_size(1024 * 1024);

**Comment by zoechi** [comment]
You can open a file and append to that file instead of `print('${record.level.name}: ${record.time}: ${record.message}');
});`

**Comment by natebosch** [comment]
The logging package is not opinionated on what you do in your log listener and we don't have support for specific use case scenarios. As @zoechi mentions you can set up file writing in the listener the same way you currently `print`.
