### ISSUE TITLE
Can Level be renamed to LogLevel?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/logging#60]
The naming of types seems inconsistent.  There's `Logger`, `LogRecord`, `LoggerHandler`... and then there's `Level`.

I either need to have a somewhat meaningless `Level` name polluting my global namespace or I need to do:

`import 'package:logging/logging.dart' as log;`

but then I end up with `log.Logger`, `log.LogRecord`, `log.LoggerHandler`, which looks a bit silly.

I don't know if there's any reasonable way to do anything about this currently, although once https://github.com/dart-lang/sdk/issues/2626 is fixed, I suppose `Level` could be a (deprecated?) `typedef` to `LogLevel`.

**Comment by natebosch** [comment]
This is tough because there isn't a good migration story. I'd be hesitant to do it even with a breaking release bump because the churn would be pretty painful.

I do think we should hold on to it, if we do get the ability to add type aliases such that we can have an incremental migration we should consider it.

**Comment by natebosch** [comment]
We do have type aliases now.

cc @kevmoo @jakemac53 for opinions on whether it's worth the churn to deprecate `Level` in favor of `LogLevel`.

**Comment by jakemac53** [comment]
IMO no we shouldn't bother, we just end up polluting the namespace further.

Individuals can also set up their own alias easily, if they choose to do so.

**Comment by kevmoo** [comment]
I TOTALLY understand the annoyance here.
I TOTALLY don't think it's worth it....

**Comment by jamesderlin** [comment]
Yeah, I agree.
