### ISSUE TITLE
logging missing within flutter compute

### ISSUE THREAD

**Issue by asssaf** [dart-lang/logging#63]
I noticed that log calls inside a static function called in `compute()` (flutter's isolate helper) are ignored.
`print()` and `debugPrint()` within the function do print as expected.
Calling the static function directly (without `compute`) logs as expected as well.

I'm using the config:
```
Logger.root.level = Level.ALL;
Logger.root.onRecord.listen((LogRecord rec) {
    debugPrint('${rec.level.name} ${rec.time} ${rec.loggerName} - ${rec.message}');
});
```

**Comment by natebosch** [comment]
Loggers don't communicate across isolates. I think the only way to set this up would be to somehow set up a log listener in the other isolate, however I'm not sure if that is possible with `compute()`.

I can't think of a good solution here....

**Comment by asssaf** [comment]
Thanks for the quick response!

Got it - so i need to do the log configuration inside the isolate.
Tried that and it's working!
