### ISSUE TITLE
Make logging package abstract

### ISSUE THREAD

**Issue by vanesyan** [dart-lang/logging#67]
Hello there!

In this issue I'd like to propose to make this package to expose abstract classes with its default implementation as it is current. The main perspective behind the proposal to make logging package APIs standardized to allow libraries authors to use any logging package they'd like and still do not affect end-users, allowing 'em use various packages and still getting consistent APIs to control all those logging without headache.

There is no concrete plan how to make it abstract, but we can decide on it, if you're interesting in it. I'd like to take effort to develop the spec, if you'd like.

BTW, the same effort you can see in the Swift language community, here is document:
https://github.com/swift-server/sswg/blob/master/proposals/0001-logging-api.md

Thanks!

**Comment by vanesyan** [comment]
cc @kevmoo. Sorry for forceful pinging, but can you, please, reply, when you will have time.

**Comment by kevmoo** [comment]
Sorry @vanesyan – I'm currently on leave.

Adding a few folks who may have thoughts: @vsmenon @natebosch @jakemac53 @grouma @munificent

**Comment by jakemac53** [comment]
It seems to me like the existing package already supports all the main goals of the swift language proposal.

What are the specific types of things that you would like to do which can't be done as it exists today?

**Comment by natebosch** [comment]
Closing since I don't think there is much to do here. All Dart classes are interfaces, so you can `implements` these classes if you need to.
