### ISSUE TITLE
Can you add an extra optional object to pass?

### ISSUE THREAD

**Issue by kmusham** [dart-lang/logging#74]
Hi, 
can you extend the logger to pass an extra optional parameters. ex: I need to pass userId.

**Comment by natebosch** [comment]
We can't customize the method signatures to particular use-specific cases. I'd recommend adding some utility methods you can use to make sure you always put `userId` into the message.

**Comment by natebosch** [comment]
I should also mention that if you pass something other than a `String` or `Function` as the message, we will `.toString()` it and also keep the original object in `LogRecord.object`. So you can log an object with a `userId` field and it will be available in the log listener.
