### ISSUE TITLE
Logging in const classes

### ISSUE THREAD

**Issue by MadSweeney46** [dart-lang/logging#83]
Is there a reason why the logging of const classes isn't supported?
For example, the class AppLocalizationsDelegate has a const initializer "const AppLocalizationsDelegate();" and lets say I'd like to log some stuff in there I am not able to create a logger like that:
static const _logger = Logger("AppLocalizationsDelegate");
I get the warning that the Logger class has no const constructor.
After I looked at the code of the logging package I realize, that it isn't easy to just make a new const constructor since you guys do some stuff that isn't available at compile time.

Now my question is:
Is there a way to get this to work on my own? I mean, I could probably write a static LogHelper that gives me the ability to log const classes but that isn't really something I want to do and I think a logging package should be able to log everywhere.
If it's not really possible to get this to work on my own, do you have any plans to enable logging for const classes in the future?
Maybe just a const constructor that always belongs to the root logger and it has less functionality than a non-const Logger constructor like it is not allowed to have children.

**Comment by natebosch** [comment]
You can log from const classes. The `Logger` instance may not be `const` and that prevents you from using it as an _instance_ field, but using it as a `static final` is fine.
