### ISSUE TITLE
How to print the stacktrace? 

### ISSUE THREAD

**Issue by MaxTenco** [dart-lang/logging#89]
I want to print the stacktrace of exception, but doesn't work.
This is the example
```dart
try{
// stuff
} catch(e, stacktrace){
 Logger('foo').severe(e, e, stacktrace);
}
```

**Comment by natebosch** [comment]
The `logging` package does not do any printing - it is up to the author to add a log listener that prints. All log listeners have access to the `stackTrace` for any record which includes one.

https://pub.dev/documentation/logging/latest/logging/LogRecord/stackTrace.html

You should edit your log listener, or file an issue if you are using one that someone else wrote. It wouldn't be defined in this package.
