### ISSUE TITLE
is isolate usage working?

### ISSUE THREAD

**Issue by niktob560** [dart-lang/logging#93]
Using [isolate bloc library](https://github.com/Maksimka101/isolate-bloc) and trying to add logs into ``onEventReceived``
main:
```Dart
main() async {
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((record) {
    print('${record.level.name}: ${record.time}: ${record.message}');
  });
  log.fine('TEST');
  await initialize(isolated);
  runApp(MyApp());
}
```
And it prints only TEST message, not messages in isolate bloc event handler

**Comment by niktob560** [comment]
``compute`` usage works fine, tested

**Comment by niktob560** [comment]
Really have no idea what was an issue, but it works fine for me now, closing.

**Comment by qgaye** [comment]
Same question, `log.info` not print in Isolate. Did you find the solution?
