### ISSUE TITLE
[Question] Relationship with dart:developer log function?

### ISSUE THREAD

**Issue by DenisGL** [dart-lang/logging#99]
The `log` function of `dart:developer` package mentions this package, and I'm wondering why.
Is it only because it could be straightforward to use `log` inside of `onRecord.listen()`, for instance?
And what would be the interest of using `log` versus `print`, or the `logging_appenders` package?

**Comment by dfdgsdfg** [comment]
Suggest simple_logging.

https://pub.dev/packages/simple_logger

It is based on logging and you can easily change `log` or `print`.

As an official document, the mobile environment needs `dart:developer`.

https://flutter.dev/docs/testing/code-debugging#logging
```
If you output too much at once, then Android sometimes discards some log lines. To avoid this, use debugPrint(), from Flutter’s foundation library. This is a wrapper around print that throttles the output to a level that avoids being dropped by Android’s kernel.

The other option for application logging is to use the dart:developer log() function. This allows you to include a bit more granularity and information in the logging output. Here’s an example:
```

Here is simple log's config.

https://github.com/mono0926/simple_logger/blob/main/lib/src/simple_logger.dart#L16
```dart
/// Select log mode.
///
/// Default is [log], which use `dart:developer`'s `log` function.
/// The `print` use [print] function.
enum LoggerMode {
  /// Use `dart:developer`'s function.
  log,

  /// Use [print] function.
  print
}
```

**Comment by natebosch** [comment]
> Is it only because it could be straightforward to use `log` inside of `onRecord.listen()`, for instance?

That's exactly what it means. The arguments were designed to be straightforward to forward a `LogRecord` but the SDK can't reference types defined in packages.

**Comment by natebosch** [comment]
> And what would be the interest of using `log` versus `print`, or the `logging_appenders` package?

`package:logging` can be used for a wide variety of use cases. `print` and `log` are use case specific.
